// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVIr2HblswAP_ovl0W5viBn6d6QblzL_0',
    appId: '1:1077025724666:web:14a14de096776cc8e3d143',
    messagingSenderId: '1077025724666',
    projectId: 'exam-seat-system',
    authDomain: 'exam-seat-system.firebaseapp.com',
    storageBucket: 'exam-seat-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIqSq2Fuiup7VCbhQ5ApG9Dx-4bHcIGNA',
    appId: '1:1077025724666:android:487a47b10d7d1c79e3d143',
    messagingSenderId: '1077025724666',
    projectId: 'exam-seat-system',
    storageBucket: 'exam-seat-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYW3t1OlTqyfdOyGZ7Ic2dMqqz0knmbBs',
    appId: '1:1077025724666:ios:987a7f646221f14ae3d143',
    messagingSenderId: '1077025724666',
    projectId: 'exam-seat-system',
    storageBucket: 'exam-seat-system.firebasestorage.app',
    iosBundleId: 'com.example.bcaExamManagment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVIr2HblswAP_ovl0W5viBn6d6QblzL_0',
    appId: '1:1077025724666:web:ad79bab71893628ce3d143',
    messagingSenderId: '1077025724666',
    projectId: 'exam-seat-system',
    authDomain: 'exam-seat-system.firebaseapp.com',
    storageBucket: 'exam-seat-system.firebasestorage.app',
  );
}
